### ISSUE TITLE
On push to GitHub: Error authenticating: failed connecting with agent

### ISSUE THREAD

**Issue by VoidPhantom** [mmtrt/gitkraken#2] opened 2018-04-08 16:54 UTC
GitKraken, installed from this snap, cannot push to GitHub. On attempt to do that, it produces the error message: “Error authenticating: failed connecting with agent”. GitKraken 3.5.1 is running on Ubuntu 17.10 and is configured to use the local SSH agent. The same version of GitKraken, when installed from the package downloaded from the GitKraken website, does not have this problem.

**Comment by mmtrt** [comment] 2018-04-08 17:09
Can you try closing gitkraken and clearing gitkraken folder from your home under snap/gitkraken then try again.

Also did you connect ssh-public-keys interface.

sudo snap connect gitkraken:ssh-public-keys

**Comment by VoidPhantom** [comment] 2018-04-08 17:16
I did that, and the problem is still there.

**Comment by mmtrt** [comment] 2018-04-08 19:16
try manually selecting the ssh key files by unchecking use local ssh agent also make sure deb version is not installed if it not works then try generating different ssh keys.

Also try deleting snap/gitkraken folder completely from home if above not working.

I just tried my manually generated ssh keys and add to git-hub from gitkraken also pulll and push a commit working fine here.

Can you give me log of any apparmor denials or errors anything would be helpfull.

**Comment by ricsdeol** [comment] 2018-04-09 15:02
Hi, I think that the same problem issue #1 

Log apparmor:

> Apr  9 12:00:40 ricsdeol-solvian kernel: [ 5990.052007] audit: type=1400 audit(1523286040.161:134): apparmor="DENIED" operation="connect" profile="snap.gitkraken.gitkraken" name="/run/user/1000/keyring/ssh" pid=30850 comm="gitkraken" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000

**Comment by mmtrt** [comment] 2018-04-09 15:14
@ricsdeol can you try the edge version

`sudo snap refresh gitkraken --edge`

then connect interfaces

`sudo snap connect gitkraken:ssh-public-keys`
`sudo snap connect gitkraken:ssh-keys`

PS: issue is confirmed snap does not have access to ssh agent so its failing  and I will be fixing it though depends on free time I get.

**Comment by mmtrt** [comment] 2018-04-11 06:12
Please @VoidPhantom @ricsdeol test and confirm it so I can push it to stable branches.

Alright now version `3.5.1 (38)` on `edge` branch has ssh agent fix 3275f477515bdeafb58b08e71d9daafced4de380

Update
`sudo snap refresh gitkraken --edge`

OR

Install
`sudo snap install gitkraken --edge`

**Note**

To load the ssh keys properly below step is needed only for the first time and if ssh keys have **Passphrase**.

* Now clear `home/snap/gitkraken` folder and don't run the app via its icon yet.

* `snap run gitkraken` from terminal and wait a bit then it will ask for your ssh key **Passphrase** type it hit enter.

* now login your account.

* profit.

**Comment by ricsdeol** [comment] 2018-04-13 20:03
Hi @mmtrt , the error continues to me :cry: 

Obs: I'm using ssh key without a passphrase :joy: and  I cleaned snap home files before run again

Logs:

Apparmor:
> Apr 13 16:57:39 ricsdeol-solvian kernel: [23683.490560] audit: type=1400 audit(1523649459.708:265): apparmor="DENIED" operation="connect" profile="snap.gitkraken.gitkraken" name="/run/user/1000/keyring/ssh" pid=14161 comm="gitkraken" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000

Snap:
>╰─○ snap run gitkraken
Initialising new SSH agent...
/snap/gitkraken/38/bin/desktop-launch: line 407: /home/ricsdeol/.ssh/environment: Permission denied
chmod: cannot access '/home/ricsdeol/.ssh/environment': No such file or directory
/snap/gitkraken/38/bin/desktop-launch: line 409: /home/ricsdeol/.ssh/environment: No such file or directory
/snap/gitkraken/38/bin/desktop-launch: line 410: /usr/bin/ssh-add: Permission denied
Node started time: 1523649263100
state:  update-not-available
EVENT: Main process loaded at 2857 ms
state:  checking-for-update
state:  update-not-available
state:  checking-for-update
EVENT: Starting initial render of foreground window at 12174 ms
state:  update-not-available
EVENT: Startup triggers started at 12542 ms

**Comment by VoidPhantom** [comment] 2018-04-14 20:42
Sorry for the late response :(
This does appear to be the same issue as ricsdeol’s. I have the same entry in the apparmor log. I installed the `3.5.1 (46)` version, and the problem is still there. I use an SSH key without a passphrase, as well.

(You seem to have already figured this out, but adding the keys manually does in fact get rid of the error.)

**Comment by mmtrt** [comment] 2018-04-15 09:09
@ricsdeol @VoidPhantom I'm afraid snapd does not allow the snap on strict confinement to use ssh-agent and installing the ssh key auto that I added the changes on `3.5.1 (38)` that did worked fine on `ArchLinux` loaded the ssh keys fine.

Anyways I'm removing all the changes except the `ssh-keys` snap interface that will needed to be connected if user wants to add the existing ssh keys manually from preferences.
So for ssh to work you guys have to manually add keys or use GK's generate keys and add to github from now on to work ssh from `preferences -> Authentication -> github.com tab -> manually add or generate and add keys`.

Thanks

**Closed as completed** 2018-04-16 16:54 UTC
Labels: bug

**Comment by pnunn** [comment] 2018-08-03 05:39
I'm not getting anywhere with this on Ubuntu 18.04. I've manually added the keys, used ssh-add to add them to a terminal then run the snap from there, tried all sorts and I can't get bitbucket to allow me access at all. 

It just keeps saying  failed connecting with agent.

**Comment by mmtrt** [comment] 2018-08-03 09:46
@pnunn its working fine here though you have to generate ssh keys from GK and add it to bitbucket.

* First connect your account then click that green button to generate the key.

![gk1](https://user-images.githubusercontent.com/2322598/43636289-188ccc28-972b-11e8-9f93-a8a6d12e9d2b.png)

* Then it will show your key then click on the highlighted button to copy your pub key it will also page where you have to add that key.

![gk2](https://user-images.githubusercontent.com/2322598/43636326-358f7a6e-972b-11e8-84b7-70384100ec88.png)

* add your earlier copied key on this page.

![gk3](https://user-images.githubusercontent.com/2322598/43636431-7a53cde4-972b-11e8-8300-6394dfcc169a.png)

**Comment by pnunn** [comment] 2018-08-04 00:24
Thank you mmtrt, that got it going. I was trying to use my existing keys, didn't think about installing a new set.  Great stuff.

The only remaining issues now is that under Wayland on Ubuntu 18.04 the snap install doesn't put an icon in the application list, nor have a icon that looks like an app one when it is running in the task bar.

Minor issues I guess, but something that might be worth a look. :)
Great app though.. love your work.
Ta. Peter.

**Comment by benwinding** [comment] 2018-08-14 02:49
I'm having this problem too, 

    GitKraken version 3.6.6

![screenshot from 2018-08-14 12-12-37](https://user-images.githubusercontent.com/11782590/44068894-82c41c70-9fbb-11e8-8efd-a3d25a7edf6c.png)

My SSH keys are on a few different servers and do not want to needlessly generate new key pairs and redeploy all the keys.

The following error occurs for me, after `sudo snap refresh gitkraken --edge`:

![selection_007](https://user-images.githubusercontent.com/11782590/44068989-e8c45f9e-9fbb-11e8-8f9a-581607650ad4.png)

`sudo snap connect gitkraken:ssh-keys` works though.

Any suggestions?

**Comment by mmtrt** [comment] 2018-08-14 07:42
when `ssh-keys` is connected then you have to manually add your exist keys from GK `Preferences` --> `Authentication` --> `github.com` --> `Load both keys` --> `add to github`.

**Comment by benwinding** [comment] 2018-08-14 10:12
@mmtrt Thanks for the reply, but I don't wan't to configure GitKraken with Github keys. I want it to use what ever the local SSH has access to.

But, when I set `Preferences --> Authentication --> General --> Use local SSH agent = checked`

I still get error: “Error authenticating: failed connecting with agent”.

**Comment by mmtrt** [comment] 2018-08-14 10:34
@benwinding local ssh agent does not work atm it have permission issues with `snap` on strict confinement, so if you don't want to use above solution then I'm afraid you have to use the non snap version of this application.

**Comment by piavgh** [comment] 2018-09-26 01:31
I tried to install non snap version (.deb) downloaded from the website.

But it can't be opened.

Also I followed this instruction:

> sudo snap refresh gitkraken --edge
> 
> then connect interfaces
> 
> sudo snap connect gitkraken:ssh-public-keys
> sudo snap connect gitkraken:ssh-keys

It doesn't work too.

**Comment by benwinding** [comment] 2018-09-26 03:38
Try the tool "gdebi" which helps install troublesome ".deb" files on Linux
distributions like Ubuntu.

    $ sudo apt install gdebi
    $ sudo gdebi ./gitkraken.deb

**Comment by piavgh** [comment] 2018-09-27 07:53
@benwinding : It doesn't work.
I'm using Ubuntu 18.04 LTS. Seems that the .deb installer is not working with 18.04 yet.

**Comment by benwinding** [comment] 2018-09-27 12:07
@piavgh 
Well for what it's worth, I'm using **Ubuntu 18.04.1 LTS**  
And **GitKraken version 4.0.1** and it successfully installed through the debian package.

**Comment by nmrshll** [comment] 2018-12-13 12:36
> I tried to install non snap version (.deb) downloaded from the website.
> 
> But it can't be opened.
> 
> Also I followed this instruction:
> 
> > sudo snap refresh gitkraken --edge
> > then connect interfaces
> > sudo snap connect gitkraken:ssh-public-keys
> > sudo snap connect gitkraken:ssh-keys
> 
> It doesn't work too.

Can't open gitkraken after a .deb installation either (on ubuntu 18.10). Installing through the .tar.gz didn't help either, same problem.
So I switchted to the snap package, and get the same error `failed connecting with agent`.

I tried this,
```
sudo snap refresh gitkraken --edge

sudo snap connect gitkraken:ssh-public-keys
sudo snap connect gitkraken:ssh-keys
```
but get these errors:
`error: snap "gitkraken" has no plug named "ssh-keys"`
`error: snap "gitkraken" has no plug named "ssh-public-keys"`

**Comment by piavgh** [comment] 2018-12-13 13:09
@nmrshll : Check this https://askubuntu.com/a/1050354/373365

Just run `sudo apt install libgnome-keyring0`

**Comment by mattzuba** [comment] 2019-01-18 02:52
My workaround for this was to adjust my /etc/X11/Xsession.d/90x11-common_ssh-agent (I'm aware I could probably have done it in my ~/.xsessionrc file, but this was quick and dirty) and modified the SSHAGENTARGS like this:
`SSHAGENTARGS="-a /home/$USER/.ssh-agent.sock"`

I logged out, logged back in, manually added my key for now (will probably automate that later), and then GK was able to use the daemon.

```
$ env | grep SSH
SSH_AUTH_SOCK=/home/mzuba/.ssh-agent.sock
SSH_AGENT_PID=4025
```
